name: Laravel Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy-via-ftp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Récupère le code depuis la branche 'main'

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"  # Version PHP utilisée par Laravel

      - name: Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --no-interaction

      - name: Install Node.js Dependencies
        run: npm install

      - name: Build assets (front-end)
        run: npm run build  # Remplace npm run prod par build selon le package.json

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Copy .env file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Check current directory
        run: pwd  # Vérifie le répertoire de travail actuel

      - name: Generate Laravel Key
        run: php artisan key:generate
        env:
          APP_ENV: production

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: 195.154.87.159
          username: gpeedheg-abidjancii
          password: ${{ secrets.FTP_PASSWORD }}  # Assurez-vous que ce secret est bien configuré dans GitHub
          local-dir: ./  # Dossier à uploader (racine du projet Laravel)
          server-dir: httpdocs/  # Essayez sans la barre oblique finale
          exclude: |
            .git*
            node_modules/
            vendor/
            storage/*.key
            .env
